### ISSUE TITLE
Initialization error on master branch

### ISSUE THREAD

**Issue by bermanmaxim** [stevengj/PyCall.jl#178] opened 2015-08-03 17:21 UTC
Using last Julia master 0.4.0-dev+6484 and last PyCall master, I have an error on initialization

```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6484 (2015-08-03 16:18 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit aff076d (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> using PyCall
WARNING: could not import Base.help into PyCall
here
WARNING: error initializing module PyCall:
ReadOnlyMemoryError()
```
I have narrowed down the line sending responsible for this initialization warning to [L.75 on pyinit.jl](https://github.com/stevengj/PyCall.jl/blob/03e1f9b770b7f16e38c190180bd2fa0868ecc044/src/pyinit.jl#L75).

Interestingly, if one builds `PyCall` before using it, initialization works.

```
julia> Pkg.build("PyCall")
INFO: Building PyCall
INFO: PyCall is using python (Python 2.7.6) at /usr/bin/python, libpython = libpython2.7

julia> using PyCall
WARNING: could not import Base.help into PyCall
```
I believe the `Base.help` error is due to the transition of Julia to the new doc system...

**Comment by stevengj** [comment] 2015-08-04 02:32
The help thing is fixed in feb4e24eb15f19fa379bcf7c844eebb3e3901814.

**Comment by stevengj** [comment] 2015-08-04 02:33
I just pushed a patch that maybe will help with the readonlyerror; please try it (`Pkg.checkout("PyCall"); Pkg.update()`)

**Comment by bermanmaxim** [comment] 2015-08-04 09:35
Thanks, the error is different now:

```
julia> using PyCall
WARNING: error initializing module PyCall:
PyCall.PyError(msg=":PyCapsule_Import", T=PyCall.PyObject(o=0x00007f3e072ae8a0), val=PyCall.PyObject(o=0x00007f3e06b0bd88), traceback=PyCall.PyObject(o=0x0000000000000000))
```

**Comment by stevengj** [comment] 2015-08-04 18:21
Can you import `datetime.datetime_CAPI` from Python?

**Comment by bermanmaxim** [comment] 2015-08-05 11:09
Yes, `from datetime import datetime_CAPI` gives no error in Python...

**Comment by swt30** [comment] 2015-08-07 19:49
@bermanmaxim, what OS are you using?

**Comment by swt30** [comment] 2015-08-10 17:50
I asked because I wondered if it could be something to do with the way the library was linked. You said it was okay after you rebuilt it, which made me think this was the same as #173. I had a similar error where a symbol wasn't being found in libpython and a package (ctypes) couldn't load, though it works in Python. Really, though, I'm in over my head here. 

Anyway, I seem to be able to get things working again by putting `Libdl.dlopen(libpython, Libdl.RTLD_LAZY|Libdl.RTLD_DEEPBIND|Libdl.RTLD_GLOBAL)` [at the top of `__init__`](https://github.com/stevengj/PyCall.jl/blob/59c2b950c2c209c291b379b26e64d3c157818a0c/src/pyinit.jl#L15). Hope that's helpful for either you or @stevengj.

**Comment by abuAnat** [comment] 2015-08-28 19:50
Have the sane problem

**Comment by bermanmaxim** [comment] 2015-08-31 11:31
On last `PyPlot` master on a fresh `julia` master installation, I don't have any errors anymore... Sorry, I don't know what fixed it.

**Comment by stevengj** [comment] 2015-09-10 20:02
Closing since the OP can no longer reproduce.

**Closed by stevengj** 2015-09-10 20:02 UTC
