### ISSUE TITLE
0.4.6-pre+35:  LoadError: UndefVarError: MacroTools not defined

### ISSUE THREAD

**Issue by olegmikul** [stevengj/PyCall.jl#270] opened 2016-05-16 20:37 UTC
Hi, 

For long time it was working fine. Today I have updated Julia and now I have an error:
```
julia> using PyCall
INFO: Precompiling module PyCall...
ERROR: LoadError: LoadError: UndefVarError: MacroTools not defined
```

**Comment by stevengj** [comment] 2016-05-16 21:11
Probably you are using the git `master` version of PyCall, i.e. you did `Pkg.checkout("PyCall")`.   The problem with this is that, with `master` versions, new dependencies aren't automatically fetched.

Either do `Pkg.free("PyCall")` to go back to the tagged version, followed by `Pkg.update()`, or explicitly run `Pkg.add("MacroTools")`.

**Comment by olegmikul** [comment] 2016-05-17 01:06
I have added MacroTools. Still same problems:
julia> Pkg.status()
X required packages:
 - MacroTools                    0.3.0
 - PyCall                        1.6.0

julia> using MacroTools
# That line is empty. No errors
julia> using PyCall
INFO: Precompiling module PyCall...
ERROR: LoadError: LoadError: UndefVarError: MacroTools not defined
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /some_path/v0.4/PyCall/src/io.jl, in expression starting on line 112
while loading /some_path/v0.4/PyCall/src/PyCall.jl, in expression starting on line 164
ERROR: Failed to precompile PyCall to /some_path/lib/v0.4/PyCall.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:400
 in require at ./loading.jl:266

Restarting Julia, removing & adding packages doesn't help.

Any help will be appreciated.

**Comment by stevengj** [comment] 2016-05-17 14:31
That's weird; I can't reproduce your problem.

Maybe your cache got corrupted somehow?  Try deleting `/some_path/lib/v0.4/*.ji` to forced everything to be recompiled.

**Comment by cstjean** [comment] 2016-05-17 15:14
That's not a "module not found" error. My guess is that something is happening during the `@capture` macroexpansion in precompilation. I'm on Julia 0.4.5 and not seeing the issue.

**Comment by floswald** [comment] 2016-05-17 15:15
Hi I'm #273. i just erased all precompileds, still same issue. i can load MacroTools, but `using Pycall` fails as above. again: I am on

```julia
julia> versioninfo()
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU           E5506  @ 2.13GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by cstjean** [comment] 2016-05-17 15:37
It's hard to debug when it's not reproducible here, but I would try `Pkg.test("MacroTools")`, and commenting out all the `precompile` lines at the top and bottom of `~/.julia/v0.4/PyCall/src/PyCall.jl`

**Comment by floswald** [comment] 2016-05-17 15:49
sure. 
Test passes, commenting out the `precompile` calls still does

```julia
julia> using PyCall
ERROR: LoadError: LoadError: UndefVarError: MacroTools not defined
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in require at ./loading.jl:259
while loading /home/florian_o/.julia/v0.4/PyCall/src/io.jl, in expression starting on line 112
while loading /home/florian_o/.julia/v0.4/PyCall/src/PyCall.jl, in expression starting on line 164

```

what's there in `while loading /home/florian_o/.julia/v0.4/PyCall/src/io.jl, in expression starting on line 112` ?

**Comment by cstjean** [comment] 2016-05-17 16:25
It's the `@pydef` call that defines the PyIO class. 

`@pydef` calls `@capture` during MacroExpansion, and `@capture(lhs,py_f_(args__))` expands into

```julia
quote  # /Users/cedric/.julia/v0.4/MacroTools/src/macro.jl, line 56:
    py_f = MacroTools.nothing
    args = MacroTools.nothing # /Users/cedric/.julia/v0.4/MacroTools/src/macro.jl, line 57:
    #73#env = MacroTools.trymatch($(Expr(:copyast, :($(QuoteNode(:(py_f_(args__))))))),lhs) # /Users/cedric/.julia/v0.4/MacroTools/src/macro.jl, line 58:
    if (#73#env MacroTools.== MacroTools.nothing) # /Users/cedric/.julia/v0.4/MacroTools/src/macro.jl, line 59:
        false
    else  # /Users/cedric/.julia/v0.4/MacroTools/src/macro.jl, line 61:
        py_f = MacroTools.get(#73#env,:py_f,MacroTools.nothing)
        args = MacroTools.get(#73#env,:args,MacroTools.nothing) # /Users/cedric/.julia/v0.4/MacroTools/src/macro.jl, line 62:
        true
    end
end
```

My guess is that this is where the problem is. You could try adding `import MacroTools` at the top of `pyclass.jl` and `io.jl`. If that doesn't work, I'm afraid that your main recourse is to trim the code down until you can isolate the error.

**Comment by cstjean** [comment] 2016-05-18 19:40
@MikeInnes Do you have any idea regarding the above? It seems to be affecting a number of PyCall users. For context, I wrote a new macro recently, `@pydef`, which uses `@capture` to generate the expansion. `@pydef` can be used by any PyCall user, but it's also used in PyCall's `__init__`, and AFAICT that's where the issue arises (even when precompilation is turned off).

@stevengj I can always rewrite `@pydef` not to use `MacroTools`...

**Comment by stevengj** [comment] 2016-05-18 20:05
Maybe change `using MacroTools: @capture` to just `using MacroTools`?

**Comment by stevengj** [comment] 2016-05-18 20:12
(The MacroTools macros sometimes generate code of the form `MacroTools.foo`, and it sounds like Julia (for *some* Julia versions) somehow does not know about the `MacroTools` module in the scope where that code is evaluated, so I'm grasping at straws here.)

Maybe if you put the `using MacroTools` up at the top of `PyCall.jl`, along with the `using Compat`, to make sure it is visible everywhere in the PyCall module?

**Comment by MikeInnes** [comment] 2016-05-18 22:05
Haven't looked into this in detail yet, but I have a hunch. I had a very similar issue in Requires.jl where a macro in `__init__` would complain `Requires not defined`, and changing the macro to reference `Main.Requires` fixed it. `__init__` is called multiple times and in the context of multiple `current_module()`s; that shouldn't affect variable scoping of course, but my guess is that the Julia compiler gives that function some kind of special handling and there's a scoping bug within that.

If you wanted to check this, you could modify PyCall's `__init__` to show `current_module()`, figure out which one barfs, and then add a `using MacroTools` to that module (which wouldn't be a fix but would demonstrate the issue).

**Comment by cstjean** [comment] 2016-05-19 03:40
Sounds promising, thanks! I think we already know which module barfs - it's PyCall itself.

@floswald @olegmikul Could you please try adding `using MacroTools` right below `module PyCall` in `~/.julia/v0.4/PyCall/src/PyCall.jl`, and see if that solves it? I can also make a debugging branch if that's not clear...

**Comment by floswald** [comment] 2016-05-19 07:33
bingo! that worked for me.

**Comment by cstjean** [comment] 2016-05-19 12:27
Perfect, thank you. I just pushed a fix to a test branch, could you please run

```julia
Pkg.checkout("PyCall", "macrotools-fix")
```

And see if that works still? Julia will probably complain because your package is dirty, so you need to undo your changes first. Go to the PyCall directory and run `git checkout src/PyCall.jl`.

If it works, I'll release the new patch later today.

**Comment by floswald** [comment] 2016-05-19 12:59
works.

**Closed** 2016-05-19 13:04 UTC

**Comment by olegmikul** [comment] 2016-05-19 23:31
Yes, works for me, too. Back to normal life! Thanks!
