### ISSUE TITLE
Julia Version 0.4.7-pre+1 ImportError - No module named site

### ISSUE THREAD

**Issue by olegmikul** [stevengj/PyCall.jl#288] opened 2016-06-21 21:49 UTC
Version 0.4.7-pre+1 (2016-06-19 17:17 UTC)
Commit 57d0834* (2 days old release-0.4)

julia> Pkg.status()
1 required packages:
 - PyCall                        1.6.2
7 additional packages:
 - BinDeps                       0.3.21
 - Compat                        0.8.1
 - Conda                         0.2.1
 - JSON                          0.6.0
 - MacroTools                    0.3.0
 - SHA                           0.1.2
 - URIParser                     0.1.3

julia> using PyCall
INFO: Recompiling stale cache file /.../PyCall.ji for module PyCall.
ImportError: No module named site

Same environment works fine for python, ipython, jupyter. 

Please help.

Thanks.

**Comment by stevengj** [comment] 2016-06-27 19:37
Duplicate of #289; please don't file duplicate issues.

**Closed by stevengj** 2016-06-27 19:37 UTC
