### ISSUE TITLE
LoadError: Failed to precompile PyCall

### ISSUE THREAD

**Issue by dpo** [stevengj/PyCall.jl#300] opened 2016-07-26 23:30 UTC
I'm running Julia 0.4.5 on OSX 10.9. I'm trying to use Plots.jl with the PyPlot backend. Here's what happens when Julia tries to precompile PyCall:

```
Assertion failed: (ctx->gensym_assigned.at(idx)), function emit_expr, file codegen.cpp, line 3155.

signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
ERROR: LoadError: Failed to precompile PyCall to /Users/dpo/.julia/lib/v0.4/PyCall.ji
 in error at /usr/local/Cellar/julia/0.4.5_1/lib/julia/sys.dylib
 in compilecache at loading.jl:400
 in require at /usr/local/Cellar/julia/0.4.5_1/lib/julia/sys.dylib
 in include at /usr/local/Cellar/julia/0.4.5_1/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/0.4.5_1/lib/julia/sys.dylib
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at /usr/local/Cellar/julia/0.4.5_1/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/0.4.5_1/lib/julia/sys.dylib
while loading /Users/dpo/.julia/v0.4/PyPlot/src/PyPlot.jl, in expression starting on line 5
```

I'm not sure how to debug this?! Please let me know what info would be helpful.

Thanks.

**Comment by stevengj** [comment] 2016-07-26 23:41
Duplicate of #269.  Just download the official Julia binary from julialang.org rather than using the Homebrew version.

**Closed by stevengj** 2016-07-26 23:41 UTC
