### ISSUE TITLE
PyPlot issues

### ISSUE THREAD

**Issue by goedman** [stevengj/PyCall.jl#281] opened 2016-05-25 14:27 UTC
Further on Ed Scheinerman's earlier message. Pkg.checkout("PyCall") does not fix this either. This is on OS X.

Below is from Plots.jl but just ```using PyPlot``` or ```using PyCall``` generates the same problem.

Regards,
Rob

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5 (2016-03-18 00:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> include("/Users/rob/.julia/v0.4/EDxMath226/examples/Math226.2/Module_03/Ex3_01.jl")
[Plots.jl] Initializing backend: pyplot
INFO: Precompiling module PyPlot...
INFO: Recompiling stale cache file /Users/rob/.julia/lib/v0.4/PyCall.ji for module PyCall.
ERROR: LoadError: InitError: cfunction: pyjlwrap_repr does not return
 in __init__ at /Users/rob/.julia/v0.4/PyCall/src/pyinit.jl:88
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
during initialization of module PyCall
while loading /Users/rob/.julia/v0.4/PyPlot/src/PyPlot.jl, in expression starting on line 5
WARNING: Couldn't initialize pyplot.  (might need to install it?)
ERROR: LoadError: Failed to precompile PyPlot to /Users/rob/.julia/lib/v0.4/PyPlot.ji
 in error at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in compilecache at loading.jl:400
 in compilecache at loading.jl:389
 in require at loading.jl:266
 [inlined code] from /Users/rob/.julia/v0.4/Requires/src/require.jl:11
 in require at /Users/rob/.julia/v0.4/Requires/src/hook.jl:17
 in _initialize_backend at /Users/rob/.julia/v0.4/Plots/src/backends/pyplot.jl:58
 in backend at /Users/rob/.julia/v0.4/Plots/src/backends.jl:117
 in plot at /Users/rob/.julia/v0.4/Plots/src/plot.jl:46
 in quiver at /Users/rob/.julia/v0.4/Plots/src/Plots.jl:228
 in streamplot at /Users/rob/.julia/v0.4/EDxMath226/src/streamplot.jl:25
 in include at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/rob/.julia/v0.4/EDxMath226/examples/Math226.2/Module_03/Ex3_01.jl, in expression starting on line 13

------------------------

In a fresh session, just using PyPlot:

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5 (2016-03-18 00:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> using PyPlot
INFO: Precompiling module PyPlot...
ERROR: LoadError: InitError: cfunction: pyjlwrap_repr does not return
 in __init__ at /Users/rob/.julia/v0.4/PyCall/src/pyinit.jl:88
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
during initialization of module PyCall
while loading /Users/rob/.julia/v0.4/PyPlot/src/PyPlot.jl, in expression starting on line 5
ERROR: Failed to precompile PyPlot to /Users/rob/.julia/lib/v0.4/PyPlot.ji
 in error at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in compilecache at loading.jl:400
 in require at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib

----------------------------------------

Or, directly:

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5 (2016-03-18 00:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> using PyCall
ERROR: InitError: cfunction: pyjlwrap_repr does not return
 in __init__ at /Users/rob/.julia/v0.4/PyCall/src/pyinit.jl:88
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
during initialization of module PyCall

**Comment by phlavenk** [comment] 2016-05-25 14:56
Hi,
I have the same problem on a new binary install of julia 0.4.5 on win64.
```
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-4669 v3 @ 2.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

the error says:
```
julia> using PyPlot
INFO: Precompiling module PyPlot...
INFO: Recompiling stale cache file e:\Users\phlavenk\juliadata\lib\v0.4\PyCall.j
i for module PyCall.
ERROR: LoadError: InitError: cfunction: pyjlwrap_repr does not return
 in __init__ at e:\Users\phlavenk\juliadata\v0.4\PyCall\src\pyinit.jl:88
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at loading.jl:109
 in require at loading.jl:235
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at client.jl:257
 in _start at client.jl:378
during initialization of module PyCall
while loading e:\Users\phlavenk\juliadata\v0.4\PyPlot\src\PyPlot.jl, in expressi
on starting on line 5
ERROR: Failed to precompile PyPlot to e:\Users\phlavenk\juliadata\lib\v0.4\PyPlo
t.ji
 in error at error.jl:21
```
Thank you for looking at the problem. In our team we heavily rely on this fantastic package.
Petr

**Comment by stevengj** [comment] 2016-05-25 15:22
Weird, this didn't show up on Travis or AppVeyor, but now I can reproduce it too.

**Comment by stevengj** [comment] 2016-05-25 15:32
Aha, it looks like this got broken by a recent change to Compat.jl

**Comment by goedman** [comment] 2016-05-25 15:56
Thanks Steven,

Indeed, ```Pkg.pin("Compat", v"0.7.18”)``` fixes the problem!

Thanks for your very quick response!

Rob

**Comment by stevengj** [comment] 2016-05-25 15:58
Will be fixed by JuliaLang/Compat.jl#211 ... hopefully that can get merged and tagged ASAP.

**Comment by stevengj** [comment] 2016-05-26 01:31
The latest tagged Compat version (`Pkg.update()`) should fix the problem.

**Closed by stevengj** 2016-05-26 01:31 UTC

**Comment by goedman** [comment] 2016-05-26 04:19
Just tried it and it works fine again with Compat v"0.7.20"! Thanks.
