### ISSUE TITLE
PyCall does not precompile 

### ISSUE THREAD

**Issue by pagnani** [stevengj/PyCall.jl#193] opened 2015-09-16 09:13 UTC
Dear all,

I'm on 

```
Julia Version 0.4.0-rc1+66
Commit 88e55be* (2015-09-16 08:37 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

```
using PyPlot
```
returns me lots of warnings and eventually
```
ERROR: LoadError: InitError: cfunction: return type of pyjlwrap_hash does not match
 in __init__ at /Users/pagnani/.julia/v0.4/PyCall/src/pyinit.jl:108
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:219
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:284
 in _start at ./client.jl:411
during initialization of module PyCall
while loading /Users/pagnani/.julia/v0.4/PyPlot/src/PyPlot.jl, in expression starting on line 5
ERROR: Failed to precompile PyPlot to /Users/pagnani/.julia/lib/v0.4/PyPlot.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:383
 in require at ./loading.jl:250
```
 It's probably worth pointing out that on 0.5 it PyPlot (and PyCall) work

Thanks for your really precious work!

Andrea

**Comment by stevengj** [comment] 2015-09-16 13:41
It works fine for me with 0.4.0-rc1 on MacOS 10.10.   Are you sure you have the latest PyPlot?  Try `Pkg.update()`.

**Comment by pagnani** [comment] 2015-09-16 13:45
I did a 
```
Pkg.update()
```
but also a more radical thing. I manually deleted in my .julia/v0.4/ both PyCall and PyPlot and did again a 
the update.

The error is always there

**Comment by stevengj** [comment] 2015-09-16 13:46
What is the output of `versioninfo(true)`?

**Comment by pagnani** [comment] 2015-09-16 13:47
```
Julia Version 0.4.0-rc1+66
Commit 88e55be* (2015-09-16 08:37 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  uname: Darwin 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64 i386
Memory: 16.0 GB (6744.03515625 MB free)
Uptime: 253578.0 sec
Load Avg:  1.44921875  1.724609375  1.8056640625
Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz:
       speed         user         nice          sys         idle          irq
#1  2500 MHz      91375 s          0 s      63494 s    1144432 s          0 s
#2  2500 MHz      18154 s          0 s       5892 s    1275186 s          0 s
#3  2500 MHz      79621 s          0 s      33789 s    1185854 s          0 s
#4  2500 MHz      18510 s          0 s       6289 s    1274425 s          0 s
#5  2500 MHz      79880 s          0 s      33932 s    1185440 s          0 s
#6  2500 MHz      18487 s          0 s       6293 s    1274436 s          0 s
#7  2500 MHz      79581 s          0 s      33861 s    1185800 s          0 s
#8  2500 MHz      18494 s          0 s       6308 s    1274406 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Environment:
  MANPATH = /opt/local/share/man:
  TERM = xterm-256color
  PATH = /usr/local/ncbi/blast/bin/:/Developer/NVIDIA/CUDA-6.5/bin:/usr/local/bin/:/opt/local/bin:/opt/local/sbin:/opt/local/libexec/gnubin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/pagnani/bin:/opt/local/lib/mysql56/bin
  XPC_FLAGS = 0x0
  HOME = /Users/pagnani
  DYLD_LIBRARY_PATH = /Users/pagnani/lib/yeppp-1.0.0/binaries/macosx/x86_64:/usr/local/cuda/lib:/Developer/NVIDIA/CUDA-6.5/lib:
  JULIA_EDITOR = /Users/pagnani/bin/xem

Package Directory: /Users/pagnani/.julia/v0.4
15 required packages:
 - CUDA                          0.1.0
 - Docile                        0.5.18
 - Gadfly                        0.3.16
 - Gurobi                        0.1.29
 - HDF5                          0.5.5
 - Jewel                         1.0.6
 - JuMP                          0.10.1
 - LsqFit                        0.0.1
 - MAT                           0.2.12
 - Markdown                      0.3.0
 - MathProgBase                  0.3.17
 - NLsolve                       0.4.0              master
 - ProfileView                   0.1.0
 - PyCall                        1.0.0
 - PyPlot                        2.1.0
57 additional packages:
 - ArrayViews                    0.6.3
 - BinDeps                       0.3.15
 - Blosc                         0.1.4
 - Cairo                         0.2.30
 - Calculus                      0.1.10
 - Codecs                        0.1.4
 - ColorTypes                    0.1.4
 - Colors                        0.5.3
 - Compat                        0.7.0
 - Compose                       0.3.15
 - Contour                       0.0.7
 - DataArrays                    0.2.18
 - DataFrames                    0.6.9
 - DataStructures                0.3.12
 - Dates                         0.4.4
 - Distances                     0.2.0
 - Distributions                 0.8.6
 - DualNumbers                   0.1.3
 - FactCheck                     0.4.0
 - FastaIO                       0.1.3
 - FixedPointNumbers             0.0.10
 - GZip                          0.2.17
 - GaussDCA                      0.0.0-             master (unregistered)
 - Graphics                      0.1.3
 - Grid                          0.3.10
 - Gtk                           0.8.6
 - GtkUtilities                  0.0.5
 - Hexagons                      0.0.4
 - Homebrew                      0.1.16
 - HttpCommon                    0.2.3
 - ImmutableArrays               0.0.10
 - Iterators                     0.1.8
 - JSON                          0.4.5
 - JuliaParser                   0.6.2
 - KernelDensity                 0.1.1
 - LNR                           0.0.1
 - LaTeXStrings                  0.1.4
 - Lazy                          0.10.0
 - Loess                         0.0.4
 - MacroTools                    0.2.0
 - MacroUtils                    0.0.0-             master (unregistered)
 - NLopt                         0.2.2
 - NaNMath                       0.1.0
 - Optim                         0.4.2
 - PDMats                        0.3.5
 - PlmDCA                        0.0.0-             master (unregistered)
 - Reexport                      0.0.3
 - Requires                      0.2.0
 - ReverseDiffSparse             0.2.10
 - SHA                           0.1.1
 - Showoff                       0.0.5
 - SortingAlgorithms             0.0.5
 - StatsBase                     0.7.2
 - StatsFuns                     0.1.3
 - URIParser                     0.1.0
 - WoodburyMatrices              0.1.1
 - Zlib                          0.1.9
```

**Comment by stevengj** [comment] 2015-09-16 21:35
Tried on another MacOS 10.10 machine with 0.4-rc1 and Anaconda, and I still can't reproduce.  :-(

**Comment by swt30** [comment] 2015-09-17 00:30
I'm finding this too, and it started after https://github.com/JuliaLang/julia/commit/1b6efc7ab297b7b8aea4d7cb0b52fb589392042b, which added binding deprecations like Uint => UInt64 (the warning that shows up just before the error on my system).

**Comment by swt30** [comment] 2015-09-17 00:51
Sorry, scratch that - I can no longer reproduce this on either release-0.4 or 0.5 after checking I was using PyCall master.

**Comment by stevengj** [comment] 2015-09-17 02:04
Ah, sounds like it was fixed by 2ff91cff447fb99b0359ec7f32af96925f9bab61.  I'll tag a new release.

**Closed** 2015-09-17 02:05 UTC

**Comment by pagnani** [comment] 2015-09-17 06:45
Works for me too.
Thanks!!!

**Comment by mkborregaard** [comment] 2015-09-17 10:15
Also worked for me! #192
